{% set name = "simpledicomtoolkit" %}
{% set version = "1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: 'https://github.com/heydude1337/{{ name }}.git'


build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - httplib2
    - pip
    - pydicom
    - python
    - pyyaml
    - simpleitk
    - python-dateutil


  run:
    - httplib2
    - pydicom
    - python
    - pyyaml
    - simpleitk
    - python-dateutil


test:
  imports:
    - SimpleDicomToolkit

about:
  home: https://github.com/heydude1337/SimpleDicomToolkit
  license: MIT
  license_family: MIT
  license_file: 
  summary: Dicom Toolkit for reading dicom files to  SimpleITK images
  doc_url: 
  dev_url: 


