{% set name = "simpledicomtoolkit" %}
{% set version = "1.3" %}
# https://pypi.io/packages/source/s/simpledicomtoolkit/simpledicomtoolkit-1.3.tar.gz
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/10/9a/7934a8ee668a3e25ba4dba739f9b770bf1890cfbb3afbc3dee0f148e0840/SimpleDicomToolkit-1.3.tar.gz
  sha256: 83cb018ece5cfc04c43879eb18be31fbe0f56caadd172119ac158c8f49e9a3c6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - httplib2
    - pip
    - pydicom
    - python
    - pyyaml
    - simpleitk
  run:
    - httplib2
    - pydicom
    - python
    - pyyaml
    - simpleitk

test:
  imports:
    - SimpleDicomToolkit

about:
  home: https://github.com/heydude1337/SimpleDicomToolkit
  license: MIT
  license_family: MIT
  license_file: 
  summary: Dicom Toolkit for reading dicom files to  SimpleITK images
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
